// Copyright (c) 2020 University of Florida
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Greg Stitt
// University of Florida
//
// Description: This application demonstrates a simple AFU pipeline that 
// streams 32-bit unsigned integers from an input array into the AFU. The AFU 
// multiplies 8 pairs of inputs (from a single cache line), accumulates the 
// results, and writes a 64-bit result to an output array. Because a full 
// cache line must be written to memory with the provided DMA, the application 
// takes as input the number of output cache lines, and then determines the 
// appropriate number of outputs and inputs to fill those cache lines. 
//
// This software allocates the input and output arrays, initializes their 
// contents, transfers the virtual addresses of the arrays, the 
// number of input cache lines to read, and a go signal to start the AFU. The
// software then waits until the AFU signals that it is done.

#include <cstdlib>
#include <iostream>
#include <cmath>

#include <opae/utils.h>

#include "AFU.h"
// Contains application-specific information
#include "config.h"
// Auto-generated by OPAE's afu_json_mgr script
#include "afu_json_info.h"

using namespace std;


void printUsage(char *name);
bool checkUsage(int argc, char *argv[], unsigned long &num_inputs);
uint64_t getCorrectOutput(volatile uint32_t input[], unsigned output_id);


int main(int argc, char *argv[]) {

  unsigned long num_output_cls;
  unsigned long num_inputs;
  unsigned long num_outputs;

  if (!checkUsage(argc, argv, num_output_cls)) {
    printUsage(argv[0]);
    return EXIT_FAILURE;
  }
  
  // There are 8 64-bit outputs per cache line.
  num_outputs = num_output_cls * 8;
  // There are 16 32-bit inputs per output.
  num_inputs = num_outputs * 16;

  try {
    AFU afu(AFU_ACCEL_UUID); 
    bool failed = false;

    // Allocate input and output arrays.
    auto input  = afu.malloc<volatile uint32_t>(num_inputs);
    auto output = afu.malloc<volatile uint64_t>(num_outputs);  

    // Initialize the input and output arrays.
    for (unsigned i=0; i < num_inputs; i++) {      
      input[i] = rand();
    }

    for (unsigned i=0; i < num_outputs; i++) {      
      output[i] = 0;
    }   
    
    // Inform the FPGA of the starting addresses of the arrays.
    afu.write(MMIO_RD_ADDR, (uint64_t) input);
    afu.write(MMIO_WR_ADDR, (uint64_t) output);

    // The FPGA DMA only handles cache-line transfers, so we need to convert
    // the input array size to cache lines. We could also do this conversion 
    // on the FPGA and transfer the number of inputs instead here.
    // The number of output cache lines is calculated by the FPGA.
    unsigned total_bytes = num_inputs*sizeof(uint32_t);
    unsigned num_cls = ceil((float) total_bytes / (float) AFU::CL_BYTES);
    afu.write(MMIO_SIZE, num_cls);

    // Start the FPGA DMA transfer (cleared automatically by the AFU).
    afu.write(MMIO_GO, 1);  

    // Wait until the FPGA is done.
    while (afu.read(MMIO_DONE) == 0) {
#ifdef SLEEP_WHILE_WAITING
      this_thread::sleep_for(chrono::milliseconds(SLEEP_MS));
#endif
    }

    // Verify the output.
    unsigned errors = 0;
    for (unsigned i=0; i < num_outputs; i++) {     
      if (output[i] != getCorrectOutput(input, i)) {
	errors ++;
      }
    }

    // Free the allocated memory.
    afu.free(input);
    afu.free(output);
        
    if (errors == 0) {
      cout << "SUCCESS: all outputs correct." << endl;
      return EXIT_SUCCESS;
    }
    
    cout << "FAILURE: " << errors << " incorrect outputs." << endl;
  }
  // Exception handling for all the runtime errors that can occur within 
  // the AFU wrapper class.
  catch (const fpga_result& e) {    
    
    // Provide more meaningful error messages for each exception.
    if (e == FPGA_BUSY) {
      cerr << "ERROR: All FPGAs busy." << endl;
    }
    else if (e == FPGA_NOT_FOUND) { 
      cerr << "ERROR: FPGA with accelerator " << AFU_ACCEL_UUID 
	   << " not found." << endl;
    }
    else {
      // Print the default error string for the remaining fpga_result types.
      cerr << "ERROR: " << fpgaErrStr(e) << endl;    
    }
  }
  catch (const runtime_error& e) {    
    cerr << e.what() << endl;
  }
  catch (const opae::fpga::types::no_driver& e) {
    cerr << "ERROR: No FPGA driver found." << endl;
  }

  return EXIT_FAILURE;
}


void printUsage(char *name) {

  cout << "Usage: " << name << " size\n"     
       << "size (positive integer for number of output cache lines to test. Every output cache line adds 8 32-bit outputs and 128 64-bit inputs.)\n"
       << endl;
}

// Returns unsigned long representation of string str.
// Throws an exception if str is not a positive integer.
unsigned long stringToPositiveInt(char *str) {

  char *p;
  long num = strtol(str, &p, 10);  
  if (p != 0 && *p == '\0' && num > 0) {
    return num;
  }

  throw runtime_error("String is not a positive integer.");
  return 0;  
}


bool checkUsage(int argc, char *argv[], unsigned long &num_output_cls) {
  
  if (argc == 2) {
    try {
      num_output_cls = stringToPositiveInt(argv[1]);
    }
    catch (const runtime_error& e) {    
      return false;
    }
  }
  else {
    return false;
  }

  return true;
}


uint64_t getCorrectOutput(volatile uint32_t input[], unsigned output_id) {

  // There are 16 inputs for every output, so find the appropriate range
  // of the input array to calculate the requested output.
  unsigned start_index = output_id*16;
  unsigned end_index = start_index + 16;

  // Perform the same computation as the AFU pipeline.
  uint64_t result = 0;
  for (unsigned i=start_index; i < end_index; i+=2) {
    result += (uint64_t) input[i] * (uint64_t) input[i+1];
  }

  return result;
}
