// Copyright (c) 2020 University of Florida
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Greg Stitt
// University of Florida
//
// This example uses the same AFU wrapper class as previous examples, but
// writes to a large number of memory-mapped addresses that the AFU implements
// across both block RAM and registers. For this example, the code uses
// the term control/status register (CSR) for the memory-mapped registers.

#include <cstdlib>
#include <iostream>

#include <opae/utils.h>

#include "AFU.h"

using namespace std;

// Auto-generated by OPAE's afu_json_mgr script
#include "afu_json_info.h"

//=========================================================
// Define the base address of the memory-mapped registers
// (i.e. control/status (CSR) registers) and block RAM that 
// was used in the RTL code.
//
// NOTE: Ideally this could be generated with a .json file just like the
// AFU_ACCEL_UUID. Without auto-generation, you must manually ensure that
// the addresses match between the RTL code and software code.
//=========================================================

// Base MMIO address of the CSRs
#define CSR_BASE_ADDR 0x0020
// The total number of CSRs
#define NUM_CSR 16

// Base MMIO address of the block RAM
#define BRAM_BASE_ADDR 0x0080
// Number of 64-bit words in the block RAM
#define BRAM_WORDS 512


int main(int argc, char *argv[]) {

  try {
    // Instantiate the AFU with the corresponding UUID.
    AFU afu(AFU_ACCEL_UUID);
    
    unsigned errors = 0;
    uint64_t csr[NUM_CSR];

    // Write a random value to each CSR and save the values in an array 
    // NOTE: in many cases, CSRs are only read by software and written by the
    // FPGA. For example, if some hardware exception occurred in the AFU, the
    // AFU would set a CSR to reflect that. This example writes to all the 
    // register solely for MMIO testing purposes.
    for (unsigned i=0; i < NUM_CSR; i++) {      
      csr[i] = rand();

      // The i*2 is needed because each address is for a 32-bit word, and the 
      // AFU only implemented 64-bit words.
      // If this extra operation is confusing, you could potentially create
      // another method in the AFU class (e.g., writeCSR) that does this
      // operation internally. Intel has reference examples that do exactly
      // this. I generally prefer to use the same MMIO addresses in software 
      // that are used in the AFU because when debugging a simulation I don't 
      // have to do any extra translation. For any realistic example, I use an
      // enum or #defines that provide meaningful names to all CSRs, so in that
      // case, the readability is the same in either approach.
      afu.write(CSR_BASE_ADDR+i*2, csr[i]);
    }

    // Read the CSR values back and verify correctness.
    for (unsigned i=0; i < NUM_CSR; i++) {      
      uint64_t result = afu.read(CSR_BASE_ADDR+i*2);
      if (result != csr[i]) {
	cerr << "ERROR: Read from MMIO register has incorrect value " << result << " instead of " << csr[i] << endl;
	errors ++;
      }
    }

    // Repeat the same tests but for the block RAM MMIO addresses.

    uint64_t bram[BRAM_WORDS];   
    // Write random values to the memory-mapped BRAM.
    for (unsigned i=0; i < BRAM_WORDS; i++) {            
      bram[i] = rand();
      afu.write(BRAM_BASE_ADDR+i*2, bram[i]);
    }

    // Read the BRAM values back and verify correctness.
    for (unsigned i=0; i < BRAM_WORDS; i++) {            
      uint64_t result = afu.read(BRAM_BASE_ADDR+i*2);
      if (result != bram[i]) {	
	cerr << "ERROR: Read from MMIO BRAM has incorrect value " << result << " instead of " << csr[i] << endl;
	errors ++;
      }
    }

    if (errors == 0) {
      cout << "All MMIO tests succeeded." << endl;
      return EXIT_SUCCESS;
    }
    else {
      cout << "MMIO tests failed." << endl;
      return EXIT_FAILURE;
    }
  }
  // Exception handling for all the runtime errors that can occur within 
  // the AFU wrapper class.
  catch (const fpga_result& e) {    
    
    // Provide more meaningful error messages for each exception.
    if (e == FPGA_BUSY) {
      cerr << "ERROR: All FPGAs busy." << endl;
    }
    else if (e == FPGA_NOT_FOUND) { 
      cerr << "ERROR: FPGA with accelerator " << AFU_ACCEL_UUID 
	   << " not found." << endl;
    }
    else {
      // Print the default error string for the remaining fpga_result types.
      cerr << "ERROR: " << fpgaErrStr(e) << endl;    
    }
  }
  catch (const runtime_error& e) {    
    cerr << e.what() << endl;
  }
  catch (const opae::fpga::types::no_driver& e) {
    cerr << "ERROR: No FPGA driver found." << endl;
  }

  return EXIT_FAILURE;
}
